### ISSUE TITLE
error installing pyafipws in debian 11 , ubuntu 18.04 , ubuntu 20.04

### ISSUE THREAD

**Issue by TRIXServer** [reingart/pyafipws#117]
I have try installing direct from github and works.

is not working using pip3 install

root@df2997bfc7ca:/# pip3 install pyafipws
Collecting pyafipws
  Using cached https://files.pythonhosted.org/packages/07/c3/c11be86d13d875ca23c4e892030f7f973af84f4faef8f5b86d14df326cd7/PyAfipWs-2.7.1874.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7n1ktnqi/pyafipws/setup.py", line 73
        print "IMPORTANTE: no se incluye el diseÃ±ador de plantillas PDF"
                                                                        ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("IMPORTANTE: no se incluye el diseÃ±ador de plantillas PDF")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7n1ktnqi/pyafipws/
root@df2997bfc7ca:/#

**Comment by juanFernigrini** [comment]
The problem is that you are running Python v3+
