### ISSUE TITLE
Compilar DLL

### ISSUE THREAD

**Issue by fjbardelli** [reingart/pyafipws#119]
# Error al compilar con py2exe laws DLL's

Estoy tratando de compilar las DLL para win32 con Windows 7 y Python 3.8

puedo usar las lib registrandolas con --register, pero no puedo generar las DLl con 

python .\setup_win.py p2y2exe

y e da el siguiente error que no se como solucionar

```console
PS C:\pyafipws> python .\setup_win.py py2exe
running py2exe
Archivo eliminado: C:\pyafipws\dist\library.zip
Archivo eliminado: C:\pyafipws\dist\pyexpat.pyd
Archivo eliminado: C:\pyafipws\dist\python38.dll
Archivo eliminado: C:\pyafipws\dist\select.pyd
Archivo eliminado: C:\pyafipws\dist\unicodedata.pyd
Archivo eliminado: C:\pyafipws\dist\win32api.pyd
Archivo eliminado: C:\pyafipws\dist\win32evtlog.pyd
Archivo eliminado: C:\pyafipws\dist\_asyncio.pyd
Archivo eliminado: C:\pyafipws\dist\_bz2.pyd
Archivo eliminado: C:\pyafipws\dist\_ctypes.pyd
Archivo eliminado: C:\pyafipws\dist\_decimal.pyd
Archivo eliminado: C:\pyafipws\dist\_elementtree.pyd
Archivo eliminado: C:\pyafipws\dist\_hashlib.pyd
Archivo eliminado: C:\pyafipws\dist\_lzma.pyd
Archivo eliminado: C:\pyafipws\dist\_multiprocessing.pyd
Archivo eliminado: C:\pyafipws\dist\_overlapped.pyd
Archivo eliminado: C:\pyafipws\dist\_queue.pyd
Archivo eliminado: C:\pyafipws\dist\_socket.pyd
Archivo eliminado: C:\pyafipws\dist\_ssl.pyd
Archivo eliminado: C:\pyafipws\dist\_testcapi.pyd
Archivo eliminado: C:\pyafipws\dist\_tkinter.pyd
Archivo eliminado: C:\pyafipws\dist\_win32sysloader.pyd

  52 missing Modules
  ------------------
? __builtin__                         imported from dbf.bridge, pkg_resources._vendor.pyparsing
? __main__                            imported from bdb, pdb, pkg_resources
? _ast_gen                            imported from pycparser._build_tables
? _common                             imported from aenum, aenum._constant, aenum._enum, aenum._tuple
? _dbm                                imported from dbm.ndbm
? _frozen_importlib                   imported from importlib, importlib.abc, zipimport
? _frozen_importlib_external          imported from importlib, importlib._bootstrap, importlib.abc, zipimport
? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? _uuid                               imported from uuid
? _winreg                             imported from pkg_resources._vendor.appdirs, platform
? aenum.Enum                          imported from dbf.constants
? aenum.IntEnum                       imported from dbf.constants
? aenum.IntFlag                       imported from dbf.constants
? aenum.NamedTuple                    imported from dbf.tables
? aenum.export                        imported from dbf.constants
? asyncio.DefaultEventLoopPolicy      imported from -
? backports.ssl_match_hostname        imported from setuptools.ssl_support
? cPickle                             imported from pycparser.ply.yacc
? cStringIO                           imported from cffi.ffiplatform
? c_ast                               imported from pycparser._build_tables
? cffi._pycparser                     imported from -
? collections.Callable                imported from cffi.api
? collections.Iterable                imported from pkg_resources._vendor.pyparsing
? collections.MutableMapping          imported from pkg_resources._vendor.pyparsing
? com.sun                             imported from pkg_resources._vendor.appdirs
? com.sun.jna                         imported from pkg_resources._vendor.appdirs
? com.sun.jna.platform                imported from pkg_resources._vendor.appdirs
? dummy.Process                       imported from multiprocessing.pool
? dummy_thread                        imported from cffi.lock
? java.lang                           imported from platform
? lextab                              imported from pycparser._build_tables
? ordereddict                         imported from pkg_resources._vendor.pyparsing
? org.python.core                     imported from copy, pickle
? org.python.modules.posix.PosixModule imported from setuptools.sandbox
? os.path                             imported from cffi.ffiplatform, ctypes._aix, distutils.file_util, os, pkg_resources, pkgutil, py_compile, pycparser.ply.yacc, sysconfig, tracemalloc, unittest, unittest.util
? pkg_resources                       imported from setuptools.archive_util, setuptools.command.bdist_egg, setuptools.command.easy_install, setuptools.command.egg_info, setuptools.command.install_scripts, setuptools.command.sdist, setuptools.dist, setuptools.installer, setuptools.package_index, setuptools.sandbox, setuptools.ssl_support, setuptools.version, setuptools.wheel
? pkg_resources.extern.appdirs        imported from pkg_resources
? pkg_resources.extern.packaging      imported from pkg_resources
? pytz                                imported from dbf.data_types
? readline                            imported from cmd, code, pdb
? resource                            imported from test.support
? setuptools.extern.ordered_set       imported from setuptools.command.sdist, setuptools.dist
? setuptools.extern.packaging         imported from setuptools.command.egg_info, setuptools.dist
? setuptools.extern.packaging.specifiers imported from setuptools.config
? setuptools.extern.packaging.tags    imported from setuptools.wheel
? setuptools.extern.packaging.utils   imported from setuptools.wheel
? setuptools.extern.packaging.version imported from setuptools.config
? thread                              imported from cffi.cparser, cffi.lock
? win32com.gen_py                     imported from win32com
? wincertstore                        imported from setuptools.ssl_support
? xmlrpclib                           imported from dbf.data_types
? yacctab                             imported from pycparser._build_tables
Building shared code archive 'dist\library.zip'.
Copy c:\program files\python38-32\python38.dll to dist
Copy C:\Program Files\Python38-32\DLLs\select.pyd to dist\select.pyd
Copy C:\Program Files\Python38-32\DLLs\_bz2.pyd to dist\_bz2.pyd
Copy C:\Program Files\Python38-32\DLLs\_lzma.pyd to dist\_lzma.pyd
Copy C:\Program Files\Python38-32\DLLs\_hashlib.pyd to dist\_hashlib.pyd
Copy C:\Program Files\Python38-32\DLLs\unicodedata.pyd to dist\unicodedata.pyd
Copy C:\Program Files\Python38-32\DLLs\_socket.pyd to dist\_socket.pyd
Copy C:\Program Files\Python38-32\DLLs\pyexpat.pyd to dist\pyexpat.pyd
Copy C:\Program Files\Python38-32\DLLs\_ssl.pyd to dist\_ssl.pyd
Copy C:\Program Files\Python38-32\DLLs\_queue.pyd to dist\_queue.pyd
Copy C:\Program Files\Python38-32\DLLs\_asyncio.pyd to dist\_asyncio.pyd
Copy C:\Program Files\Python38-32\lib\site-packages\win32\_win32sysloader.pyd to dist\_win32sysloader.pyd
Copy C:\Program Files\Python38-32\lib\site-packages\win32\win32api.pyd to dist\win32api.pyd
Copy C:\Program Files\Python38-32\lib\site-packages\win32\win32evtlog.pyd to dist\win32evtlog.pyd
Copy C:\Program Files\Python38-32\DLLs\_elementtree.pyd to dist\_elementtree.pyd
Copy C:\Program Files\Python38-32\DLLs\_ctypes.pyd to dist\_ctypes.pyd
Copy C:\Program Files\Python38-32\DLLs\_tkinter.pyd to dist\_tkinter.pyd
Copy C:\Program Files\Python38-32\DLLs\_testcapi.pyd to dist\_testcapi.pyd
Copy C:\Program Files\Python38-32\DLLs\_decimal.pyd to dist\_decimal.pyd
Copy C:\Program Files\Python38-32\DLLs\_multiprocessing.pyd to dist\_multiprocessing.pyd
Copy C:\Program Files\Python38-32\DLLs\_overlapped.pyd to dist\_overlapped.pyd
Traceback (most recent call last):
  File "C:\Program Files\Python38-32\lib\site-packages\py2exe\runtime.py", line 553, in copy_files
    assert mod.__file__.endswith(EXTENSION_TARGET_SUFFIX)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\setup_win.py", line 624, in <module>
    setup(name="PyAfipWs",
  File "C:\Program Files\Python38-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files\Python38-32\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\Python38-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Program Files\Python38-32\lib\site-packages\pyafipws-3.8.3046-py3.8.egg\pyafipws\nsis.py", line 191, in run
    py2exe.run(self)
  File "C:\Program Files\Python38-32\lib\site-packages\py2exe\distutils_buildexe.py", line 192, in run
    self._run()
  File "C:\Program Files\Python38-32\lib\site-packages\py2exe\distutils_buildexe.py", line 273, in _run
    builder.build()
  File "C:\Program Files\Python38-32\lib\site-packages\py2exe\runtime.py", line 271, in build
    self.copy_files(destdir)
  File "C:\Program Files\Python38-32\lib\site-packages\py2exe\runtime.py", line 556, in copy_files
    assert (mod.__file__ in self.mf.real_dlls() or mod.__file__ in  self.mf.extension_dlls())
AssertionError
PS C:\pyafipws>
```

Si a alguien le paso y me da una mano agradecido.

Saludos

**Comment by estudiosistemas** [comment]
> # Error al compilar con py2exe laws DLL's
> Estoy tratando de compilar las DLL para win32 con Windows 7 y Python 3.8
> 
> puedo usar las lib registrandolas con --register, pero no puedo generar las DLl con
> 
> python .\setup_win.py p2y2exe
> 
> y e da el siguiente error que no se como solucionar
> 
> PS C:\pyafipws> python .\setup_win.py py2exe
> running py2exe
> Archivo eliminado: C:\pyafipws\dist\library.zip
> Archivo eliminado: C:\pyafipws\dist\pyexpat.pyd
> Archivo eliminado: C:\pyafipws\dist\python38.dll
> Archivo eliminado: C:\pyafipws\dist\select.pyd
> Archivo eliminado: C:\pyafipws\dist\unicodedata.pyd
> Archivo eliminado: C:\pyafipws\dist\win32api.pyd
> Archivo eliminado: C:\pyafipws\dist\win32evtlog.pyd
> Archivo eliminado: C:\pyafipws\dist\_asyncio.pyd
> Archivo eliminado: C:\pyafipws\dist\_bz2.pyd
> Archivo eliminado: C:\pyafipws\dist\_ctypes.pyd
> Archivo eliminado: C:\pyafipws\dist\_decimal.pyd
> Archivo eliminado: C:\pyafipws\dist\_elementtree.pyd
> Archivo eliminado: C:\pyafipws\dist\_hashlib.pyd
> Archivo eliminado: C:\pyafipws\dist\_lzma.pyd
> Archivo eliminado: C:\pyafipws\dist\_multiprocessing.pyd
> Archivo eliminado: C:\pyafipws\dist\_overlapped.pyd
> Archivo eliminado: C:\pyafipws\dist\_queue.pyd
> Archivo eliminado: C:\pyafipws\dist\_socket.pyd
> Archivo eliminado: C:\pyafipws\dist\_ssl.pyd
> Archivo eliminado: C:\pyafipws\dist\_testcapi.pyd
> Archivo eliminado: C:\pyafipws\dist\_tkinter.pyd
> Archivo eliminado: C:\pyafipws\dist\_win32sysloader.pyd
> 
>   52 missing Modules
>   ------------------
> ? __builtin__                         imported from dbf.bridge, pkg_resources._vendor.pyparsing
> ? __main__                            imported from bdb, pdb, pkg_resources
> ? _ast_gen                            imported from pycparser._build_tables
> ? _common                             imported from aenum, aenum._constant, aenum._enum, aenum._tuple
> ? _dbm                                imported from dbm.ndbm
> ? _frozen_importlib                   imported from importlib, importlib.abc, zipimport
> ? _frozen_importlib_external          imported from importlib, importlib._bootstrap, importlib.abc, zipimport
> ? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
> ? _uuid                               imported from uuid
> ? _winreg                             imported from pkg_resources._vendor.appdirs, platform
> ? aenum.Enum                          imported from dbf.constants
> ? aenum.IntEnum                       imported from dbf.constants
> ? aenum.IntFlag                       imported from dbf.constants
> ? aenum.NamedTuple                    imported from dbf.tables
> ? aenum.export                        imported from dbf.constants
> ? asyncio.DefaultEventLoopPolicy      imported from -
> ? backports.ssl_match_hostname        imported from setuptools.ssl_support
> ? cPickle                             imported from pycparser.ply.yacc
> ? cStringIO                           imported from cffi.ffiplatform
> ? c_ast                               imported from pycparser._build_tables
> ? cffi._pycparser                     imported from -
> ? collections.Callable                imported from cffi.api
> ? collections.Iterable                imported from pkg_resources._vendor.pyparsing
> ? collections.MutableMapping          imported from pkg_resources._vendor.pyparsing
> ? com.sun                             imported from pkg_resources._vendor.appdirs
> ? com.sun.jna                         imported from pkg_resources._vendor.appdirs
> ? com.sun.jna.platform                imported from pkg_resources._vendor.appdirs
> ? dummy.Process                       imported from multiprocessing.pool
> ? dummy_thread                        imported from cffi.lock
> ? java.lang                           imported from platform
> ? lextab                              imported from pycparser._build_tables
> ? ordereddict                         imported from pkg_resources._vendor.pyparsing
> ? org.python.core                     imported from copy, pickle
> ? org.python.modules.posix.PosixModule imported from setuptools.sandbox
> ? os.path                             imported from cffi.ffiplatform, ctypes._aix, distutils.file_util, os, pkg_resources, pkgutil, py_compile, pycparser.ply.yacc, sysconfig, tracemalloc, unittest, unittest.util
> ? pkg_resources                       imported from setuptools.archive_util, setuptools.command.bdist_egg, setuptools.command.easy_install, setuptools.command.egg_info, setuptools.command.install_scripts, setuptools.command.sdist, setuptools.dist, setuptools.installer, setuptools.package_index, setuptools.sandbox, setuptools.ssl_support, setuptools.version, setuptools.wheel
> ? pkg_resources.extern.appdirs        imported from pkg_resources
> ? pkg_resources.extern.packaging      imported from pkg_resources
> ? pytz                                imported from dbf.data_types
> ? readline                            imported from cmd, code, pdb
> ? resource                            imported from test.support
> ? setuptools.extern.ordered_set       imported from setuptools.command.sdist, setuptools.dist
> ? setuptools.extern.packaging         imported from setuptools.command.egg_info, setuptools.dist
> ? setuptools.extern.packaging.specifiers imported from setuptools.config
> ? setuptools.extern.packaging.tags    imported from setuptools.wheel
> ? setuptools.extern.packaging.utils   imported from setuptools.wheel
> ? setuptools.extern.packaging.version imported from setuptools.config
> ? thread                              imported from cffi.cparser, cffi.lock
> ? win32com.gen_py                     imported from win32com
> ? wincertstore                        imported from setuptools.ssl_support
> ? xmlrpclib                           imported from dbf.data_types
> ? yacctab                             imported from pycparser._build_tables
> Building shared code archive 'dist\library.zip'.
> Copy c:\program files\python38-32\python38.dll to dist
> Copy C:\Program Files\Python38-32\DLLs\select.pyd to dist\select.pyd
> Copy C:\Program Files\Python38-32\DLLs\_bz2.pyd to dist\_bz2.pyd
> Copy C:\Program Files\Python38-32\DLLs\_lzma.pyd to dist\_lzma.pyd
> Copy C:\Program Files\Python38-32\DLLs\_hashlib.pyd to dist\_hashlib.pyd
> Copy C:\Program Files\Python38-32\DLLs\unicodedata.pyd to dist\unicodedata.pyd
> Copy C:\Program Files\Python38-32\DLLs\_socket.pyd to dist\_socket.pyd
> Copy C:\Program Files\Python38-32\DLLs\pyexpat.pyd to dist\pyexpat.pyd
> Copy C:\Program Files\Python38-32\DLLs\_ssl.pyd to dist\_ssl.pyd
> Copy C:\Program Files\Python38-32\DLLs\_queue.pyd to dist\_queue.pyd
> Copy C:\Program Files\Python38-32\DLLs\_asyncio.pyd to dist\_asyncio.pyd
> Copy C:\Program Files\Python38-32\lib\site-packages\win32\_win32sysloader.pyd to dist\_win32sysloader.pyd
> Copy C:\Program Files\Python38-32\lib\site-packages\win32\win32api.pyd to dist\win32api.pyd
> Copy C:\Program Files\Python38-32\lib\site-packages\win32\win32evtlog.pyd to dist\win32evtlog.pyd
> Copy C:\Program Files\Python38-32\DLLs\_elementtree.pyd to dist\_elementtree.pyd
> Copy C:\Program Files\Python38-32\DLLs\_ctypes.pyd to dist\_ctypes.pyd
> Copy C:\Program Files\Python38-32\DLLs\_tkinter.pyd to dist\_tkinter.pyd
> Copy C:\Program Files\Python38-32\DLLs\_testcapi.pyd to dist\_testcapi.pyd
> Copy C:\Program Files\Python38-32\DLLs\_decimal.pyd to dist\_decimal.pyd
> Copy C:\Program Files\Python38-32\DLLs\_multiprocessing.pyd to dist\_multiprocessing.pyd
> Copy C:\Program Files\Python38-32\DLLs\_overlapped.pyd to dist\_overlapped.pyd
> Traceback (most recent call last):
>   File "C:\Program Files\Python38-32\lib\site-packages\py2exe\runtime.py", line 553, in copy_files
>     assert mod.__file__.endswith(EXTENSION_TARGET_SUFFIX)
> AssertionError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File ".\setup_win.py", line 624, in <module>
>     setup(name="PyAfipWs",
>   File "C:\Program Files\Python38-32\lib\distutils\core.py", line 148, in setup
>     dist.run_commands()
>   File "C:\Program Files\Python38-32\lib\distutils\dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "C:\Program Files\Python38-32\lib\distutils\dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "C:\Program Files\Python38-32\lib\site-packages\pyafipws-3.8.3046-py3.8.egg\pyafipws\nsis.py", line 191, in run
>     py2exe.run(self)
>   File "C:\Program Files\Python38-32\lib\site-packages\py2exe\distutils_buildexe.py", line 192, in run
>     self._run()
>   File "C:\Program Files\Python38-32\lib\site-packages\py2exe\distutils_buildexe.py", line 273, in _run
>     builder.build()
>   File "C:\Program Files\Python38-32\lib\site-packages\py2exe\runtime.py", line 271, in build
>     self.copy_files(destdir)
>   File "C:\Program Files\Python38-32\lib\site-packages\py2exe\runtime.py", line 556, in copy_files
>     assert (mod.__file__ in self.mf.real_dlls() or mod.__file__ in  self.mf.extension_dlls())
> AssertionError
> PS C:\pyafipws>
> Si a alguien le paso y me da una mano agradecido.
> 
> Saludos

Hola, en la pull request deje algunas soluciones a problemas que tuve https://github.com/reingart/pyafipws/pull/120

**Comment by reingart** [comment]
En el action de GitHub se compila el instalador automaticamente; ya estan actualizado y los test pasan.

¿Podrian probar esos artefactos generados?

Ver https://github.com/reingart/pyafipws/pull/120#issuecomment-2692968063
