### ISSUE TITLE
No funciona el parametro /dbf

### ISSUE THREAD

**Issue by catrielr** [reingart/pyafipws#18]
Usando la ultima version de pyafipws

Con la version dbf 0.96.003 tengo la siguente salida:
Excepcion: table encabeza.dbf is closed
Traceback (most recent call last):
  File "c:\pyafipws-master\rece1.py", line 642, in <module>
    }, open(salida,"w"))
  File "c:\pyafipws-master\rece1.py", line 268, in escribir_factura
    guardar_dbf(formatos, agrega, conf_dbf)
  File "c:\pyafipws-master\utils.py", line 719, in guardar_dbf
    reg = tabla.current()
  File "c:\pyafipws-master\dbf\ver_2.py", line 2301, in current
    self._nav_check()
  File "c:\pyafipws-master\dbf\ver_2.py", line 4585, in _nav_check
    raise DbfError('table %s is closed' % self.filename)
## dbf.ver_2.DbfError: table encabeza.dbf is closed

Con la version dbf 0.88.019 tengo la siguente salida:

C:\clipper>python c:\pyafipws-master\rece1.py c:\pyafipws-master\rece.ini /dbf /ult 1 4002
Consultar ultimo numero:
Ultimo numero:  3982

setting imptotalq 44.54
setting monedaidc PES
setting tiporegxaq 0
setting fechavencp
Excepcion: 'fechacbte:  no such field in table'
setting imptotalq 44.54
setting monedaidc PES
setting tiporegxaq 0
setting fechavencp
setting emisiontip CAE
setting fechaservh
setting reproceso
setting fechaservd
Traceback (most recent call last):
  File "c:\pyafipws-master\rece1.py", line 642, in <module>
    }, open(salida,"w"))
  File "c:\pyafipws-master\rece1.py", line 268, in escribir_factura
    guardar_dbf(formatos, agrega, conf_dbf)
  File "c:\pyafipws-master\utils.py", line 724, in guardar_dbf
    reg.write_record(**r)
  File "c:\pyafipws-master\dbf\tables.py", line 393, in write_record
    yo.gather_fields(kwargs)
  File "c:\pyafipws-master\dbf\tables.py", line 331, in gather_fields
    raise FieldMissing(key)
dbf.exceptions.FieldMissing: 'tiporeg:  no such field in table'

**Comment by catrielr** [comment]
C:\pyafipws-master>python rece1.py rece.ini  /dbf /prueba
Excepcion: encabeza.dbf not in read/write mode, unable to append records
Traceback (most recent call last):
  File "rece1.py", line 642, in <module>
    }, open(salida,"w"))
  File "rece1.py", line 268, in escribir_factura
    guardar_dbf(formatos, agrega, conf_dbf)
  File "C:\pyafipws-master\utils.py", line 716, in guardar_dbf
    registro = tabla.append(r)
  File "c:\Python27\lib\site-packages\dbf\ver_2.py", line 5132, in append
    raise DbfError('%s not in read/write mode, unable to append records' % meta.filename)
dbf.ver_2.DbfError: encabeza.dbf not in read/write mode, unable to append records
