### ISSUE TITLE
pythoncom error: ERROR: server.policy could not create an instance.

### ISSUE THREAD

**Issue by Wruaro** [reingart/pyafipws#40]
hOLA

Al querer instanciar algún objeto en un puesto con win 10 de 64 bits estamos teniendo los siguientes errores:

pythoncom error: ERROR: server.policy could not create an instance.

Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 121, in CreateInstance
  File "win32com\server\policy.pyc", line 719, in resolve_func
KeyError: ''
pythoncom error: Unexpected gateway error

Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 121, in CreateInstance
  File "win32com\server\policy.pyc", line 719, in resolve_func
KeyError: ''
pythoncom error: CPyFactory::CreateInstance failed to create instance. (80004005)

se les ocurre que puede ser

desde ya muchas gracias

**Comment by reingart** [comment]
El `KeyError` aparentemente sucede porque Python no está pudiendo leer el registro de Windows (generalmente por problemas con las politicas de seguridad / permisos de acceso, o directamente esta dañado / mal instalado).

Concretamente ver Permisos en Windows: http://www.sistemasagiles.com.ar/trac/wiki/ManualPyAfipWs#Windows

En el foro también ha sido reportado, ver https://groups.google.com/d/msg/pyafipws/FEhS0Sfnv-s/MEXMoGmvBQAJ para otra solución tentativa.

Si eso no lo soluciona, tendrían que modificar levemente la biblioteca pywin32, módulo win32com, server, policy (generalmente `C:\Python27\lib\site-packages\win32com\server\policy.py`), funcion `CreateInstance` y `resolve_func` para que no explote si no encuentra la entrada en el registro.

Ver el siguiente `diff -u policy.py policy_ok.py`:

```diff
--- policy.py	2011-03-19 07:51:20.000000000 -0300
+++ policy_ok.py	2018-02-17 22:21:51.054186000 -0300
@@ -120,6 +120,8 @@
                                       regPolicy % clsid)
     policy = resolve_func(policy)
   except win32api.error:
+    policy = None
+  if not policy:
     policy = DefaultPolicy
 
   try:
@@ -716,7 +718,8 @@
     module = _import_module(mname)
     return getattr(module, fname)
   except ValueError: # No "." in name - assume in this module
-    return globals()[spec]
+    if spec in globals():
+      return globals()[spec]
```

Pueden probarlo, habría que ver si con este problema superado no surjan otros errores de permisos en el resto del código de pywin32.
Idealmente sería necesario identificar el problema de origen, más allá de esta posible mitigación.

Yo particularmente no lo pude reproducir en ningun windows 10, desde toda información técnica es más que bienvenida.
