### ISSUE TITLE
Compatibilidad con Python 3

### ISSUE THREAD

**Issue by urbinacity** [reingart/pyafipws#41]
Actualmente el modulo no es compatible con la sintaxis de Python 3, es factible migrar el codigo, usando por ejemplo este script [2to3](https://docs.python.org/2/library/2to3.html)? 

```
pip install -r test.txt
Collecting git+https://github.com/reingart/pyafipws@master (from -r test.txt (line 11))
  Cloning https://github.com/reingart/pyafipws (to master) to /tmp/pip-ofmrekod-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-ofmrekod-build/setup.py", line 78
        print "IMPORTANTE: no se incluye el diseÃ±ador de plantillas PDF"
                                                                        ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-ofmrekod-build/
```

A partir de la versión 10, Odoo migró todo el codigo a Python 3.

**Comment by urbinacity** [comment]
Issue duplicado >> [https://github.com/reingart/pyafipws/issues/34](https://github.com/reingart/pyafipws/issues/34)
